language: node_js
node_js:
  - "10"

cache: yarn

install: yarn
script:
  - yarn build
  - yarn test
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: yarn build
      before_deploy:
        - cd lib
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true  # 为了防止 Travis CI 清理额外的文件夹并删除你做的改变
        on:
          tags: true